### ISSUE TITLE
What is the login password?

### ISSUE THREAD

**Issue by it19862** [HueByte/MyThingsSaver#13]
What is the login password?

![15 12 2022_22-55-10](https://user-images.githubusercontent.com/18245828/207954681-d2524d57-34f0-42a3-86d6-c64d21dad018.png)
![15 12 2022_22-53-59](https://user-images.githubusercontent.com/18245828/207954684-fa1fed39-0935-4a58-9525-b2491f125423.png)

**Comment by HueByte** [comment]
That seems like dev branch. Assuming you configured your MTS right it's the username and password you submitted during registration.
Currently I'm rewritting MTS, so I am unsure at what state you're using it right now, I'll make release once everything is ready
